version: '2'
services:
    php56:
        container_name: web-php56
        image: php56
        build: ./php56
        volumes:
            - ./volumes/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./volumes/logs/nginx:/var/log/nginx
            - ./volumes/www:/var/www
            - ./volumes/scripts:/scripts
        ports:
            - "8888:80"
        links:
            - postgres
            - mysql
            - redis
            - memcached

    postgres:
        container_name: web-postgres
        image: postgres
        build: ./postgres
        volumes:
            - ./volumes/data/postgres:/var/lib/postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: webocker
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root

    mysql:
        container_name: web-mysql
        image: mysql
        build: ./mysql
        volumes:
            - ./volumes/data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: webocker
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root

    redis:
        container_name: web-redis
        image: redis
        build: ./redis
        volumes:
            - ./volumes/data/redis:/var/lib/redis
        ports:
            - "6379:6379"

    memcached:
        container_name: web-memcached
        image: memcached
        build: ./memcached
        volumes:
            - ./volumes/data/memcached:/var/lib/memcached
        ports:
            - "11211:11211"
